baseURL = ""
languageCode = "en-us"
title = "Yatima Inc"
themesDir = "themes"
theme = "hugo-hero-theme"
relativeUrls = true

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Yatima Inc is developing the programming language Yatima."
    meta_og_title = "Yatima Inc"
    meta_og_type = "website"
    meta_og_description = "Yatima Inc is developing the programming language Yatima."


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
